batch_size: 1
cfg: DMFNet_GDL_all
ckpt_dir: ./ckpts
criterion: GeneralizedDiceLoss
dataset: BraTSDataset
eps: 1.0e-05
gpu: 0,1,2,3
name: DMFNet_GDL_all
net: DMFNet
net_params:
  c: 4
  channels: 128
  groups: 16
  n: 32
  norm: sync_bn
  num_classes: 4
num_epochs: 500
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 1.0e-05
restore: model_last.pth
save_freq: 50
seed: 1024
start_iter: 0
test_data_dir: /data2/liuxiaopeng/Data/BraTS2018/Test
test_transforms: Compose([ Pad((0, 0, 0, 5, 0)), NumpyType((np.float32, np.int64)),
  ])
train_data_dir: /data2/liuxiaopeng/Data/BraTS2018/Train
train_list: all.txt
train_transforms: Compose([ RandCrop3D((128*2,128*2,16)), NumpyType((np.float32, np.int64)),
  ])
valid_data_dir: /data2/liuxiaopeng/Data/BraTS2018/Valid
valid_freq: 100
valid_list: valid.txt
weight_type: square
workers: 8
